### ISSUE TITLE
Multipart form upload for quests

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-quest-creator#228]
Large quests currently break when an upload is attempted. We should switch to a multipart upload to allow for mega-quests to exist.

**Comment by toddmedema** [comment]
Looks like it's an issue with our body-parser lib; we should be able to increase the limit, but there seems to be a bug. Added an issue: https://github.com/expressjs/body-parser/issues/235

**Comment by dougwilson** [comment]
Since you have https://github.com/ExpeditionRPG/expedition-quest-creator/blob/23b72809f36171f279ef637be975aacacd1f047f/app.js#L22 which accepts _every single type_, that's the only body parser that will ever get invoked. You can simply delete the two below it and add your limit to that once, since it's the only one that will do anything.

**Comment by toddmedema** [comment]
@dougwilson thanks for the prompt answer!

Can confirm, that fixes it.

Question: is there a way to do all types EXCEPT one? In this case, we'd like it to default to text parsing, but in the special case of JSON, use `app.use(bodyParser.json({ type:'json/*' }));` - perhaps via the ability to use regexes for the type field?

Not breaking for our app, since it's (apparently, hah) been using just text parsing this entire time, but it does seem like that might be a useful addition?

**Comment by dougwilson** [comment]
Just reverse the order of the app.use, so the more specific type is first.
