### ISSUE TITLE
Publish more metrics

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-quest-creator#339]
Publish more QC metrics on eg collaborative editing, notes bar usage, context editor, etc

**Comment by toddmedema** [comment]
Macro thought: Given our limited programming bandwidth and large community with lots of great feedback, we hear about issues from fans faster than we could find them in analytics, and have an endless queue of good ideas to work on... so I wonder if usage analytics makes sense at our team size.

Thinking about the three examples (collaborative / simultaneous editing, notes bar and context editor), they all seem like a similar case we're trying to analyze: are people using this feature?

To which, I think there are a few general ways we could measure "feature usage":
- On a quest level to Quests DB table, ie a boolean flag of it's used or not
  - Pro: No double measurements, an accurate way to measure who is using it since it's attached to quests / accounts
  - Con: Would only show up in published quests (unless we started recording all created quests into the DB), wouldn't give any additional metrics like length of use
- On a per-event level to Google Analytics, such as a second person joining or opening the notes panel
  - Pro: Easy to code, more data
  - Con: Not attached to user info, tons of double measurements (ie 100 uses could be 1 person 100 times)
  - Thought: We could add Firebase to the Quest Creator UI for more detailed analytics, ie we could attach user + quest information to each of these events, and then slice and dice later. More work, though.

**Comment by toddmedema** [comment]
Backlogging for now

**Comment by smartin015** [comment]
Not needed.
