### ISSUE TITLE
Instruction style enforcement (for later content detection)

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-quest-creator#341]
Style enforcement of roleplay instructions (e.g. "draw x loot", "heal x health"). Dynamically detect when the user is likely to be doing these things and suggest a common style.

Besides being more consistent for players, also enables us in the future to detect / act on these instructions programmatically (both for crawler / balance detection, and for other quest/app implementations)

**Comment by toddmedema** [comment]
Any suggestions for simple but effective detection implementations? Feel like just looking for "loot" or "health" would be a good enough indication of if they're telling users to draw loot or heal health, then we can check if it complies with the style (perhaps "draw (word-number) tier # loot" and "heal # health")

While we're here, should do the same for persona as well, ie "gain # persona" / "lose # persona" based on looking for the word "persona"

Also, should this be an error (that prevents publishing) or a warning? The former feels a bit heavy-handed, but I don't think we currently have the ability to do the latter, so that might be out of scope.
