### ISSUE TITLE
Combat parameter: damage / surge on first round

### ISSUE THREAD

**Issue by ArcanaIreanol** [ExpeditionRPG/expedition-quest-creator#437]
*Migrated to expeditionrpg/expedition#320 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

Would be nice to be able to make foes having the first turn. Let's say the adventurers are ambushed by a band of bandits in a dark street. Those bandits should deal damage first and then let the adventurers play.
I know we can simulate that by writing in the card before combat something like "everyone take X damage" but then we lose the automatic combat difficulty system (depending on the number of adventurers)

Same goes for the surge. Be able to make it appear on first round for example
Something like

```
_combat_ (#someid) {"surprise-round": true, "surprise-round": true}
```

**Comment by toddmedema** [comment]
@ArcanaIreanol dig it! We'd been doing the `> Take X damage`, but you're absolutely right that it would be better to loop into the combat system.

Think it might make sense to make the attributes use case agnostic, something like `surgeOnFirstRound` and `damageOnFirstRound` so that it doesn't imply that they can only be used for surprise rounds.

**Comment by toddmedema** [comment]
Moving this to the backlog; trying to avoid adding new features to the language unless there's multiple users requesting since it increases maintenance burden.
