### ISSUE TITLE
Option to ignore playtester warnings

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-quest-creator#455]
*Migrated to expeditionrpg/expedition#326 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

It's a little frustrating to have warning signs that don't actually indicate badness (e.g. using ability cards as part of an instruction, but not about gaining/losing abilities). We should have some way to suppress the warnings if we know better than the playtester.

**Comment by toddmedema** [comment]
Interesting. Were you thinking:
1. ignore all warnings
2. ignore all warnings of this type
3. ignore this specific warning

From a UI perspective, wouldn't be too hard to show all of those options, but I think 3 might be the hardest... after all, we can't anchor it to the line # since that'll change, as will the line contents itself. Though, I suppose we could have it save the specific problem text instead of the whole line contents, which would make it more robust to changes and also give us some more debugging info about lines that people think should be fine (if we logged that)

**Comment by smartin015** [comment]
Specifically thinking of #3 - suppressing warnings known to be useless. We could get around the line number problem by adding this feature to the language (e.g. via comment).

**Comment by toddmedema** [comment]
Very complex for the value, backlogging
