### ISSUE TITLE
"Ignore" spellcheck option + publish blocker

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-quest-creator#488]
*Migrated to expeditionrpg/expedition#339 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

We could prevent users from publishing if their quest has one or more spelling mistakes that they haven't explicitly allowed for their quest.

**Comment by toddmedema** [comment]
Implementation-wise, we'll probably want to save this as another realtime field (thinking an array of strings that the user has opted to ignore for the quest)

Note that we'll also need to figure out how to interact directly with a misspelling, ideally by right clicking the word specifically and showing a dropdown. If we do that, we could then also suggest 1-3 other words that are closest to it so that you don't have to Google the correct spelling!
