### ISSUE TITLE
multi-line instructions

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-quest-creator#62]
- what's the best syntax? require a `>` on every line, including requiring it on the paragraph break lines? Or, if there are two `> text` right below each other, should they be part of the same `instruction`, as two separate paragraphs? Or, like programming comments, should there be a separate syntax for instructions nodes that should carry on over line breaks?
- tests!

**Comment by danielwiktorcyk** [comment]
I've added a page in which there are three commands right after the other, e.g. before engaging in combat, the Zombie Hand grabs a Frying Pan and delivers unexpected blows!

```
> Each adventurer tosses a d20. 
> If d20 < 5, the adventurer takes 4 damage
> If d20 = 20, the adventurer parries and delivers a blow of 5 damage to the Zombie Hand!
```

In this way, I get three separate paragraphs with three different adventurer icons for each step, which works. 

It might be worth considering adding indentations / numbers for "if" steps, as in for the example below, it would look cool if it were to look more like the following, _but all on the same screen page_ 

+ Each adventurer tosses a d20. 
  - If d20 < 5, the adventurer who rolled it takes 4 damage
  + If d20 = 20, the adventurer who rolled it parries and delivers a blow of 5 damage to the Zombie Hand!

Also, can the icon be changed to a different icon for specific instructional bullet? _e.g. one for the d20, one for melee abilities, etc_

In this way, I like the syntax for separate instructions rather than having them grouped together

**Comment by toddmedema** [comment]
Hmm, interesting! In that sense, I could see the instruction elements functioning kind of like bulleted list elements, where simply indenting the `> instruction` would be enough to indent it in the app

As far as icons go, we actually have most of the code set up to accept different icons (initially, with any of the core expedition icons - adventurer, roll, melee, bandit, etc). But, one thing we've been stuck on is figuring out a good syntax for icons. I think the best thing we've come up with so far would be something like `> [bandit] Draw a Tier 1 Bandit1`, a la how markdown handles images, and how we'd do images in general in quests: https://github.com/Fabricate-IO/expedition-quest-creator/issues/46

**Comment by danielwiktorcyk** [comment]
True, indenting the `> instruction` bullet-ed branching therefore wouldn't be mixed up with the indentation previously reserved for `* choices `, so that could work! 

`[icon]` would definitely be a comfortable syntax to use. Maybe this syntax could be expanded to incorporate future art / design for each page, such as having it include `[icon=bandit]` ; `[background=magic] `; etc, to incorporate any visual elements that may be added later on.

**Comment by toddmedema** [comment]
Oooh, interesting idea, having parameters within the `[]`! That'd probably be the only sensible way to scaling it to different types of media... would get way too confusing with different brackets or obscure symbols to import music vs background vs inline vs block

**Comment by toddmedema** [comment]
Happy Holidays!

Been thinking more on the indentation side of things... I'm a little divided on if we should allow indented instructions. Essentially, thinking that we want to avoid encouraging the creation of huge / complex instructions blocks involving lots of if's and branches that would be better handled by the existing choices and branches systems. Does that sound reasonable?

(part of our goal when designing the Quest Language has been to focus on simplicity - both for actually writing the quest, and designing it to prevent writers from painting themselves into an overly-complex corner - even if it occasionally means missing out on an advanced-users-only feature)

**Comment by danielwiktorczyk** [comment]
Happy Holidays to you too! 

On second thought, indented instructions may be a little unnecessary to boot! I do see how it would lead to / allow for convoluted systems, and the branches definitely could handle all that mess if need be.

**Comment by smartin015** [comment]
Current behavior is markdown-style, i.e. having something like:

```
> line 1
  line 2
```

Causes both lines to be in a single instruction ("line1 line2"). We also have support for instruction icons now, so:

```
> [roll] You roll a die!
```

Shows the d20 icon as the instructional bullet.
